import type { Metadata } from "next";
import "./globals.css";
import Cabecalho from "@/components/Header";
import Footer from "@/components/Footer";
import bgImage from "@/img/bg-img.jpg"; 

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="pt-br">
      <body
        className="bg-cover bg-center min-h-screen text-white"
        style={{ backgroundImage: `url(${bgImage.src})` }} 
      >
        <div className="flex flex-col min-h-screen bg-black bg-opacity-70">
          <Cabecalho />
          <main className="flex-grow container mx-auto p-6 md:p-8 lg:p-10">
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
